defmodule Uptrack.Reports.ReportEmail do
  @moduledoc """
  Renders and sends weekly report emails.
  """

  import Swoosh.Email

  alias Uptrack.Mailer

  @from {"Uptrack", "reports@uptrack.app"}

  def deliver(user, report_data) do
    subject = "Weekly Uptime Report — #{report_data.overall_uptime}% uptime"

    body = build_body(report_data)

    email =
      new()
      |> to({user.name || user.email, user.email})
      |> from(@from)
      |> subject(subject)
      |> html_body(body)
      |> text_body(build_text_body(report_data))

    Mailer.deliver(email)
  end

  defp build_body(report) do
    monitors_html =
      report.monitor_breakdown
      |> Enum.map(fn m ->
        color = if m.uptime >= 99.5, do: "#22c55e", else: if(m.uptime >= 95, do: "#eab308", else: "#ef4444")
        """
        <tr>
          <td style="padding:8px;border-bottom:1px solid #eee">#{m.name}</td>
          <td style="padding:8px;border-bottom:1px solid #eee;color:#{color};font-weight:600">#{m.uptime}%</td>
          <td style="padding:8px;border-bottom:1px solid #eee;color:#888">#{m.status}</td>
        </tr>
        """
      end)
      |> Enum.join()

    """
    <div style="font-family:sans-serif;max-width:600px;margin:0 auto;color:#333">
      <h2 style="color:#7553FF">Weekly Uptime Report</h2>
      <p style="color:#666">#{report.period}</p>

      <div style="background:#f9fafb;border-radius:8px;padding:20px;margin:20px 0">
        <div style="display:flex;gap:30px">
          <div>
            <div style="font-size:32px;font-weight:700;color:#{if report.overall_uptime >= 99.5, do: "#22c55e", else: "#eab308"}">#{report.overall_uptime}%</div>
            <div style="color:#888;font-size:14px">Overall Uptime</div>
          </div>
          <div>
            <div style="font-size:32px;font-weight:700">#{report.active_monitors}</div>
            <div style="color:#888;font-size:14px">Active Monitors</div>
          </div>
          <div>
            <div style="font-size:32px;font-weight:700;color:#{if report.incident_count > 0, do: "#ef4444", else: "#22c55e"}">#{report.incident_count}</div>
            <div style="color:#888;font-size:14px">Incidents</div>
          </div>
        </div>
      </div>

      <table style="width:100%;border-collapse:collapse">
        <thead>
          <tr style="text-align:left">
            <th style="padding:8px;border-bottom:2px solid #ddd">Monitor</th>
            <th style="padding:8px;border-bottom:2px solid #ddd">Uptime</th>
            <th style="padding:8px;border-bottom:2px solid #ddd">Status</th>
          </tr>
        </thead>
        <tbody>#{monitors_html}</tbody>
      </table>

      <p style="margin-top:20px;font-size:13px;color:#999">
        This report was generated on #{Calendar.strftime(report.generated_at, "%B %d, %Y")} by Uptrack.
      </p>
    </div>
    """
  end

  defp build_text_body(report) do
    monitors_text =
      report.monitor_breakdown
      |> Enum.map(fn m -> "  #{m.name}: #{m.uptime}% (#{m.status})" end)
      |> Enum.join("\n")

    """
    Weekly Uptime Report — #{report.period}

    Overall Uptime: #{report.overall_uptime}%
    Active Monitors: #{report.active_monitors}
    Incidents: #{report.incident_count}

    Monitor Breakdown:
    #{monitors_text}

    Generated by Uptrack on #{Calendar.strftime(report.generated_at, "%B %d, %Y")}
    """
  end
end
