import Config

# Configure your databases - all point to same DB initially for painless migration
config :uptrack, Uptrack.AppRepo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "uptrack_dev",
  parameters: [search_path: "app,public"],
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :uptrack, Uptrack.ObanRepo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "uptrack_dev",
  parameters: [search_path: "oban,public"],
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 5

config :uptrack, Uptrack.ResultsRepo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "uptrack_dev",
  parameters: [search_path: "results,public"],
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Legacy repo config (for migration compatibility)
config :uptrack, Uptrack.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "uptrack_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :uptrack, UptrackWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Kyk+x1I8oJ3/7lnZBSYPqXK6I95GBiVbbQ2L+w9UW9jA8kJwDKyvO7dUngFm4pul",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:uptrack, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:uptrack, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :uptrack, UptrackWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/uptrack_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :uptrack, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Paddle billing (sandbox — always enabled in dev with sandbox credentials)
config :uptrack, :paddle,
  api_key: System.get_env("PADDLE_API_KEY", "pdl_sdbx_apikey_01khkczdjaxqarfk17jv77ycfd_cfWqzP0GYkFwaeg6RRH7m7_A6K"),
  webhook_secret: System.get_env("PADDLE_WEBHOOK_SECRET", "pdl_ntfset_01khkdq69fbn5tsaq2agf9c49r_rpYogp57hMobtpvIbhjqLZRafei4qluk"),
  base_url: System.get_env("PADDLE_BASE_URL", "https://sandbox-api.paddle.com"),
  checkout_url: System.get_env("PADDLE_CHECKOUT_URL", "https://sandbox-checkout.paddle.com"),
  price_id_pro: System.get_env("PADDLE_PRICE_ID_PRO", "pri_01khkcqn8pv207r6j8qnjfmj5t"),
  price_id_pro_annual: System.get_env("PADDLE_PRICE_ID_PRO_ANNUAL", "pri_01khkcqn8pv207r6j8qnjfmj5t"),
  price_id_team: System.get_env("PADDLE_PRICE_ID_TEAM", "pri_01khkcrv2b6a5kc9cftsh503gc"),
  price_id_team_annual: System.get_env("PADDLE_PRICE_ID_TEAM_ANNUAL", "pri_01khkcrv2b6a5kc9cftsh503gc")
