defmodule UptrackWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :uptrack

  # The session will be stored in the cookie, signed and encrypted.
  @session_options [
    store: :cookie,
    key: "_uptrack_key",
    signing_salt: "UTz/hMyF",
    encryption_salt: "x8Rk3nPq",
    same_site: "None",
    secure: true,
    domain: ".uptrack.app"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :uptrack,
    gzip: not code_reloading?,
    only: UptrackWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :uptrack

    plug Phoenix.LiveDashboard.RequestLogger,
      param_key: "request_logger",
      cookie_key: "request_logger"
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    body_reader: {UptrackWeb.Plugs.CacheBodyReader, :read_body, []}

  plug Plug.MethodOverride
  plug Plug.Head
  plug UptrackWeb.Plugs.CORS
  plug Plug.Session, @session_options
  plug UptrackWeb.Router
end
